### ISSUE TITLE
'int' object is not iterable when using the inbound

### ISSUE THREAD

**Issue by elijah2352** [Raukk/tf-keras-surgeon#1]
Hello,

I'm getting the following error when I run the lenet_mnist.py example. 

I am running tensorflow 1.14.0

Traceback (most recent call last):
  File "lenet_mnist.py", line 103, in <module>
    main()
  File "lenet_mnist.py", line 75, in main
    model = delete_channels(model, layer, high_apoz_channels)
  File "/data/tf-keras-surgeon/src/tfkerassurgeon/operations.py", line 105, in delete_channels
    return surgeon.operate()
  File "/data/tf-keras-surgeon/src/tfkerassurgeon/surgeon.py", line 152, in operate
    sub_output_nodes = utils.get_node_inbound_nodes(node)
  File "/data/tf-keras-surgeon/src/tfkerassurgeon/utils.py", line 91, in get_node_inbound_nodes
    for i, node_index in enumerate(node.node_indices)]
TypeError: 'int' object is not iterable

**Comment by Raukk** [comment]
Thank you for this report!

Is this issue happening in the first training loop? 

I have reproduced the issue after the print message `original model loss:` when using versions `1.14.0-rc1` and `1.14.1-dev20190622` with a `TypeError: 'int' object is not iterable` exception at `for i, node_index in enumerate(node.node_indices)`

I also confirmed that this issue is not in TF `1.13.1` (version I previously tested).
(Note: I've only been checking `-gpu` versions)


I'll check back if I need more details. 
I'll notify you when it's resolved for you to test and confirm.

Again, thanks for the report.


PS.
Sorry for the formality, I'm used to corporate work.

Do you have any additional examples you'd like to see added?

I'm curious about how are you intending to use the Pruning, if you don't mind sharing?

**Comment by shortcipher3** [comment]
I'm seeing the same error when running with TensorFlow 2.0.0-beta1.

I would like to see a 2.0 example added and/or get some direction on how to create a pruning example myself.

I'm interested in pruning some cnns to see if I can get them to perform inference faster on something like a raspberry pi.

**Comment by Raukk** [comment]
This specific issue is from a change somewhere in Tensorflow after version 1.13.1, and I am working to isolate it and resolve it. 

> I'm seeing the same error when running with TensorFlow 2.0.0-beta1.
Thank you, I'll be sure to test that once I have a fix.
This project is intended to support 2.0 and future versions, however, because 2.0 is still Beta/Release Candidate, it has not been a priority. 

> I would like to see a 2.0 example added and/or get some direction on how to create a pruning example myself.

Keras did not have any huge API changes in 2.0 (that I am aware of). In fact, the majority of the changes I'm aware of are pushing things to be more standardized with Keras or to be more Keras like.

> I'm interested in pruning some cnns to see if I can get them to perform inference faster on something like a raspberry pi.

This can surely help with that, are you also doing the training on RasPi, or only inference?


As a temporary workaround, you can install Tensorflow version 1.13.0 which should work fine with that example. The Keras API and usage should be similar to the TF 2.0 code, so updating once I resolve this issue should be easy.
Something like:
pip install tensorflow==1.13.0
or
pip install tensorflow-gpu==1.13.0

**Comment by shortcipher3** [comment]
> Keras did not have any huge API changes in 2.0 (that I am aware of). In fact, the majority of the changes I'm aware of are pushing things to be more standardized with Keras or to be more Keras like.

That is good news.

> are you also doing the training on RasPi, or only inference?

Only inference

I've replaced:

`! pip install -U tf-nightly-gpu==1.13.0`

with:

`! pip install -U tensorflow-gpu==1.13.0rc2`

It runs fine.

**Comment by Raukk** [comment]
Thanks for the update.

I'll try to resolve the core issue ASAP so that you can move forward with 2.0

Good luck on the testing and training. 

When it comes to inference, you can also see if weight quantization would help. 

Additionally, there are some accelerator chips like the Intel compute stick or the Google coral TPU that can improve the speed of embed devices like a Raspi.

I'd love to hear how this works for your application or if there are any features that would make it easier.

**Comment by Raukk** [comment]
I've Been digging into this, and a lot of things in Tensorflow have changed, and I'm still tracking down all the breaking changes.

I technically fixed the part of the issue that is mentioned here, but because the actual pruning is not working, it doesn't matter until I get the other items fixed. 

I also added a note in the readme about Versions newer than 1.13.1

**Comment by Raukk** [comment]
I have fixed the issue and updated the Example. 

Version 0.2.1 has this fix and is available through Pip. (https://pypi.org/project/tfkerassurgeon/)

I am also working on some cool changes and new features that should make the tool more powerful for network pruning. 

Thanks again for your feedback and support.
